name: GitLab4J CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:

  build-jdk8:
    name: "Build JDK 8"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: adopt-hotspot
          java-version: 8
      - name: GitLab4j verify
        id: gitlab4j-verify
        run: |
          ./gradlew build --console=PLAIN --stacktrace
